### PR TITLE
Feat/create connect wallet button

### LINKED ISSUE #25: [FE]: Create Connect Wallet Button logic
> [!IMPORTANT]
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Create Connect Wallet Button Logic  

## Description  
Implement the logic for a "Connect Wallet" button to enable users to connect to Stellar wallets. The button should support wallets such as **Albedo**, **Rabet**, **Freighter**, and other Stellar-compatible wallets.  

## Requirements  
1. **Component Location**:  
   - The Component is located in `components/ui/ConnectWalletButton.tsx` (you have to edit the .tsx file).  

2. **Functionality**:  
   - Allow users to select and connect to their preferred Stellar wallet.  
   - Detect and handle cases where a wallet is not installed.  
   - Use best practices for Stellar wallet integrations.  

3. **UI Design**:  
   - Ensure the button is styled consistently with the application's theme, Follow the provided [Figma design](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0).  
   - Use clear and concise text like “Connect Wallet” or similar.  

4. **Wallet Support**:  
   - Integrate with popular Stellar wallets, including but not limited to:  
     - **Albedo**  
     - **Rabet**  
     - **Freighter**  
     - **Xbull**  

### Image:
Captura de pantalla 2024-12-08 a las 7 39 47 p  m

### PR DESCRIPTION
**Pull request by armandocodecr**
# 🚀 StarShop Pull Request

- [x] Closes #25 
- [] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [x] Evidence attached
- [] Commented the code

---

## 📝 Changes description

1. I created all the configuration files and hooks necessary to maintain the correct functioning of the wallet.
2. I used zustand so that the connected status is maintained between tabs.
3. I created the button with the requested design
4. I used the button inside the landing page.

---

## 📸 Evidence (A photo is required as evidence)

[Issue #25 | Create Connect Wallet Button logic | Demo Video](https://www.youtube.com/watch?v=LV9r14ELHT4)

---

## ⏰ Time spent breakdown

4 HOURS

---

## 🌌 Comments

1. I placed the button to connect the wallet next to the “Register now” button. This is because there is not yet a navbar to place the “Connect Wallet” button. The developer in charge of creating the navbar will only have to move the “ConnectWalletButton” component to the corresponding navbar and that's it, it will work exactly the same.
2. The wallet “Rabet” and any other wallet appears as “Not available” because I don't have it installed, but it doesn't mean that it can't be connected.

---

Thank you for contributing to StarShop, we are glad that you have chosen us as your project of choice and we hope that you continue to contribute to this great project, so that together we can make our mark at the top!

### CODE REVIEW

**Comment by KevinLatino** [comment]
Hi @armandocodecr i can't access to the video, pls check it and share it with me again

**Comment by armandocodecr** [comment]
@KevinLatino My mistake, I posted the wrong link. You should be able to see it now

**Comment by KevinLatino** [comment]
Pls, resolve merge conflicts

**Comment by KevinLatino** [comment]
LGTM, thanks for contributing!

**Pull request merged**
