### PR TITLE
[FE]: Create Loading Spinner

### PR DESCRIPTION
**Pull request by FrankiePower**
### Description
This pull request adds a loading spinner functionality to the previously empty `LoadingSpinner` component. The implementation introduces dynamic loading behavior and is also in accordance with the application's branding

### CODE REVIEW

**Comment by KevinLatino** [comment]
Please, don't implement it, just create it in the LoadingSpinner.tsx File, take an screenshot and upload it

**Comment by FrankiePower** [comment]
Screenshot from 2024-12-12 21-32-19

**Comment by KevinLatino** [comment]
Pls, make it smaller. Also here you have an example of what we are looking for: 

Captura de pantalla 2024-12-12 a las 2 37 21 p  m

**Comment by FrankiePower** [comment]
Screenshot from 2024-12-12 21-53-13

**Comment by KevinLatino** [comment]
Please, don't add more file, pls deleted micro/Rolling file.

and please use the code provided in the issue comment, just change the color to purple

**Comment by KevinLatino** [comment]
Looks pretty good, but please delete the useless files

**Comment by KevinLatino** [comment]
Great, thanks for contributing!

**Pull request merged**
